Fix CS0234 and CS0246 errors in MediationConsentManager
- Changed ConsentType enum (which doesn't exist) to string
- Added ConsentManager dependency injection to MediationConsentManager
- Updated GetConsentTypeSafe() to use consentManager.GetConsentType()
- Changed comparisons from ConsentType.Personalized to "Personalized"
- Updated AdsManager to pass consentManager when creating MediationConsentManager
- Synced changes to Assets/Admob/ folder

Resolves:
- error CS0234: The type or namespace name 'Mediation' does not exist
- error CS0246: The type or namespace name 'ConsentType' could not be found